# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.bedard: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

# Thymeleaf Configuration (✅ Fix for template not found)
#spring:
#  thymeleaf:
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#    check-template-location: true
#    cache: false  # Disable caching for development/testing
---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:mysql://portfolio-db:3306/portfolio-db?useSSL=false&allowPublicKeyRetrieval=true
    username: user
    password: pwd
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect

  sql:
    init:
      platform: mysql
      mode: always

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SPRING_MAIL_USERNAME}
#    password: ${SPRING_MAIL_PASSWORD}
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}

server.port: 8080

spring.datasource.hikari.initializationFailTimeout: 60000