spring:
  config:
    activate:
      on-profile: prod

#  thymeleaf:
#    enabled: true
#    prefix: classpath:/templates/
#    suffix: .html
#    check-template-location: true
#    cache: false  # Disable caching for development/testing

  datasource:
    url: ${MYSQL_URL}  # Railway's database URL (set in Railway environment variables)
    username: ${MYSQLUSER}
    password: ${MYSQLPASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none  # Prevents accidental schema changes in production

  sql:
    init:
      mode: never  # Prevents SQL scripts from running on startup

#  mail:
#    host: smtp.gmail.com
#    port: 587
#    username: ${SPRING_MAIL_USERNAME}
#    password: ${SPRING_MAIL_PASSWORD}
#    properties:
#      mail.smtp.auth: true
#      mail.smtp.starttls.enable: true

okta:
  oauth2:
    issuer: ${OKTA_OAUTH2_ISSUER}
    audience: ${OKTA_OAUTH2_AUDIENCE}


server:
  port: ${PORT:8080}  # Railway dynamically assigns a port

